# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.3
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: ["--fix"]
    # Sort imports
    - id: ruff
      name: ruff (imports)
      types_or: [ python, pyi ]
      args: ["check", "--select", "I", "--fix"]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]