# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.3
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: ["--fix"]
      exclude: "mascon_cube/geodesynet"
    # Sort imports
    - id: ruff
      name: ruff (imports)
      types_or: [ python, pyi ]
      args: ["check", "--select", "I", "--fix"]
      exclude: "mascon_cube/geodesynet"
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
      exclude: "mascon_cube/geodesynet"
- repo: local
  hooks:
    - id: downscale-notebook-images
      name: Downscale notebook images
      entry: python .hooks/downscale_images_in_notebook.py
      language: system
      types: [jupyter]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-added-large-files
      name: Check files are < 512 kb (notebooks excluded)
      args: ["--maxkb=512"]
      exclude: "notebooks"
    - id: check-added-large-files
      name: Check notebooks are < 1 Mb
      args: ["--maxkb=1024"]
