name: masconcube
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - nvidia::cudatoolkit = 11.3
  - python ~= 3.12.6
  - pip ~= 25.0.1
  - pytorch::pytorch ~= 2.4.0
  - pytorch::torchvision ~= 0.19.0
  - numpy ~= 2.2.3
  - lazy_import ~= 0.2.2
  - scipy ~= 1.15.2
  # dev
  - pre-commit ~=4.1.0
  - pyvista ~= 0.44.2
  - ipykernel ~= 6.29.5
  - tensorboard ~= 2.19.0

  - pip:
    - tetgen ~= 0.6.5
    - -e .