name: masconcube
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - nvidia::cudatoolkit = 11.3
  - python ~= 3.12.6
  - pip
  - pytorch::pytorch ~= 2.4.0
  - pytorch::torchvision ~= 0.19.0
  - numpy ~= 2.2.3
  - lazy_import ~= 0.2.2

  - pip:
    - -e --no-compile .