name: masconcube
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - nvidia::cudatoolkit = 11.3
  - python ~= 3.12.6
  - pip
  - pytorch::pytorch
  - pytorch::torchvision
  - numpy ~= 2.2.3
  - lazy_import
  # dev
  - pre-commit ~=4.1.0
  - pyvista ~= 0.44.2
  - ipykernel ~= 6.29.5
  - tensorboard ~= 2.19.0

  - pip:
    - tetgen
    - -e .