name: masconcube
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - nvidia::cudatoolkit = 11.3
  - python ~= 3.12.6
  - pip ~= 25.0.1
  - pytorch::pytorch ~= 2.4.0
  - pytorch::torchvision ~= 0.19.0
  - numpy ~= 2.2.3
  - lazy_import ~= 0.2.2
  - scipy ~= 1.15.2
  - seaborn ~= 0.13.2
  - torchquad ~= 0.4.1

  - pip:
    - tetgen ~= 0.6.5
    - -e --no-compile .